/**
 * Cart.tsx
 *
 * Shopping Cart Page Component
 *
 * This component provides a complete shopping cart experience for Pokemon card purchases.
 * It handles cart management including viewing items, removing items, clearing the cart,
 * and processing purchases. The component integrates with the backend API for all cart
 * operations and provides a seamless user experience with loading states, error handling,
 * and navigation.
 *
 * Key Features:
 * - Display all items in the user's cart with images and prices
 * - Calculate and display total cart value
 * - Remove individual items from cart
 * - Clear entire cart at once
 * - Purchase all items in cart
 * - Navigate to card browsing page and user collection
 * - Handle empty cart state
 * - Real-time cart updates after operations
 *
 * API Integration:
 * - GET /api/cart - Fetch user's cart items
 * - DELETE /api/cart/:id - Remove specific item
 * - DELETE /api/cart/clear - Clear all items
 * - POST /api/cart/purchase - Complete purchase
 *
 * Authentication:
 * All API calls require Bearer token authentication from localStorage
 */

// Import React hooks for state management and side effects
import { useState, useEffect } from "react";
// Import navigation hook for programmatic routing
import { useNavigate } from "react-router-dom";

/**
 * CartItem Interface
 *
 * TypeScript interface defining the structure of a cart item object.
 * Each cart item represents a Pokemon card that a user has added to their cart.
 * This matches the backend API response format for cart items.
 */
interface CartItem {
    /**
     * Unique identifier for this cart entry
     * Generated by the backend when item is added to cart
     * Used for removing specific items from cart
     */
    id: string;

    /**
     * Reference to the original card's database ID
     * Links cart item to the card in the cards collection
     * Used for purchase processing and inventory tracking
     */
    card_id: string;

    /**
     * Display name of the Pokemon card
     * Example: "Pikachu", "Charizard", "Mewtwo"
     * Shown in cart UI for user identification
     */
    card_name: string;

    /**
     * Price of the card in USD
     * Stored as a number for calculations
     * Displayed with 2 decimal places in UI
     */
    card_price: number;

    /**
     * URL path to the card's image
     * Points to external or CDN-hosted image
     * Displayed as thumbnail in cart list
     */
    card_image: string;
}
/**
 * Cart Functional Component
 *
 * Main component that renders the shopping cart page.
 * Manages all cart state and handles cart-related operations.
 */
function Cart() {
    // ============================================================
    // STATE MANAGEMENT
    // ============================================================

    /**
     * Array of cart items fetched from the backend
     * Initially empty array, populated by fetchCart() on mount
     * Updated after remove/clear/purchase operations
     * Type: CartItem[] - defined by CartItem interface above
     */
    const [cartItems, setCartItems] = useState<CartItem[]>([]);

    /**
     * Loading state for initial cart data fetch
     * true: Shows loading spinner while fetching cart
     * false: Displays cart contents or empty state
     * Set to true initially, changed to false after API call completes
     */
    const [loading, setLoading] = useState(true);

    /**
     * Purchase operation in-progress state
     * true: Disables purchase/clear buttons and shows "Processing..."
     * false: Enables user interactions
     * Prevents duplicate purchases by disabling buttons during API call
     */
    const [purchasing, setPurchasing] = useState(false);

    /**
     * Navigation function from react-router-dom
     * Used for programmatic navigation to other pages
     * navigate("/path") - Changes current route
     * Examples: navigate("/pokemon-cards"), navigate("/my-collection")
     */
    const navigate = useNavigate();

    // ============================================================
    // LIFECYCLE EFFECTS
    // ============================================================

    /**
     * Component Mount Effect
     *
     * Runs once when the component first renders (empty dependency array [])
     * Fetches the user's cart data from the backend API
     * This ensures cart is loaded and displayed when page opens
     */
    useEffect(() => {
        // Call API to fetch cart items
        fetchCart();
    }, []); // Empty array = run only on mount, not on re-renders

    // ============================================================
    // API FUNCTIONS
    // ============================================================

    /**
     * Fetch Cart Items from Backend
     *
     * Retrieves all items in the authenticated user's shopping cart.
     * Uses JWT token from localStorage for authentication.
     * Updates component state with fetched cart items.
     *
     * API Endpoint: GET http://localhost:8000/api/cart
     * Authentication: Required (Bearer token)
     * Response: Array of CartItem objects
     *
     * Error Handling:
     * - Network errors: Logged to console, user sees empty cart
     * - Auth errors: Logged to console (should redirect to login in production)
     * - Loading state ensures smooth user experience during fetch
     */
    const fetchCart = async () => {
        // Retrieve JWT authentication token from browser's localStorage
        // Token is stored during login and used for all authenticated requests
        const token = localStorage.getItem("token");

        try {
            // Make GET request to cart endpoint
            // Backend validates token and returns cart items for authenticated user
            const res = await fetch("http://localhost:8000/api/cart", {
                headers: {
                    // Include Bearer token in Authorization header for authentication
                    // Format: "Bearer <jwt_token>"
                    "Authorization": `Bearer ${token}`
                }
            });

            // Parse JSON response body to JavaScript object/array
            // Expected format: Array of CartItem objects
            const data = await res.json();

            // Update React state with fetched cart items
            // This triggers re-render to display cart contents
            setCartItems(data);
        } catch (err) {
            // Catch network errors, JSON parsing errors, or other exceptions
            // Log error details for debugging
            // User will see empty cart state (cartItems remains empty array)
            console.error("Failed to fetch cart:", err);
        } finally {
            // Finally block always executes, even if try or catch runs
            // Set loading to false to hide loading spinner and show cart UI
            // This ensures loading state is updated regardless of success/failure
            setLoading(false);
        }
    };

    /**
     * Remove Single Item from Cart
     *
     * Deletes a specific cart item by its ID.
     * Shows confirmation dialog before removal.
     * Refreshes cart after successful deletion.
     *
     * @param cartItemId - Unique ID of the cart item to remove
     * @param cardName - Name of the card for confirmation message
     *
     * API Endpoint: DELETE http://localhost:8000/api/cart/{cartItemId}
     * Authentication: Required (Bearer token)
     * Response: Success/failure status
     *
     * Flow:
     * 1. Ask user to confirm removal
     * 2. Send DELETE request to backend
     * 3. Show success message
     * 4. Refresh cart to reflect changes
     */
    const removeFromCart = async (cartItemId: string, cardName: string) => {
        // Show browser confirmation dialog before deletion
        // Returns true if user clicks "OK", false if "Cancel"
        // Early return if user cancels - prevents deletion
        if (!confirm(`Remove ${cardName} from cart?`)) return;

        // Get authentication token from localStorage
        const token = localStorage.getItem("token");

        try {
            // Send DELETE request to remove specific cart item
            // URL includes cartItemId to identify which item to delete
            const res = await fetch(`http://localhost:8000/api/cart/${cartItemId}`, {
                method: "DELETE", // HTTP DELETE method for resource deletion
                headers: {
                    // Include Bearer token for authentication
                    "Authorization": `Bearer ${token}`
                }
            });

            // Check if response status is in 200-299 range (success)
            if (res.ok) {
                // Show success message to user
                alert("✅ Removed from cart");

                // Refresh cart data to update UI
                // This re-fetches from backend to ensure consistency
                fetchCart();
            }
        } catch (err) {
            // Handle network errors or other exceptions
            // Show user-friendly error message
            alert("Failed to remove item from cart");
        }
    };

    /**
     * Clear Entire Cart
     *
     * Removes all items from the user's cart at once.
     * Shows confirmation dialog before clearing.
     * Updates local state immediately on success.
     *
     * API Endpoint: DELETE http://localhost:8000/api/cart/clear
     * Authentication: Required (Bearer token)
     * Response: Success/failure status
     *
     * Flow:
     * 1. Ask user to confirm clearing entire cart
     * 2. Send DELETE request to clear endpoint
     * 3. Show success message
     * 4. Update state to empty array (faster than re-fetching)
     *
     * Note: Uses setCartItems([]) instead of fetchCart() for immediate UI update
     */
    const clearCart = async () => {
        // Show confirmation dialog to prevent accidental cart clearing
        // User must confirm they want to remove all items
        if (!confirm("Are you sure you want to clear your cart?")) return;

        // Retrieve authentication token from localStorage
        const token = localStorage.getItem("token");

        try {
            // Send DELETE request to clear cart endpoint
            // This removes all cart items for the authenticated user
            const res = await fetch("http://localhost:8000/api/cart/clear", {
                method: "DELETE", // DELETE method to remove all cart items
                headers: {
                    // Include Bearer token for user authentication
                    "Authorization": `Bearer ${token}`
                }
            });

            // Check if operation succeeded (status 200-299)
            if (res.ok) {
                // Show success notification to user
                alert("✅ Cart cleared");

                // Immediately update state to empty array
                // This is faster than calling fetchCart() since we know result
                // UI updates instantly to show empty cart state
                setCartItems([]);
            }
        } catch (err) {
            // Handle network errors or API failures
            // Show user-friendly error message
            alert("Failed to clear cart");
        }
    };

    /**
     * Purchase All Items in Cart
     *
     * Processes the purchase of all cart items.
     * Transfers cart items to user's collection.
     * Clears cart and redirects to collection page on success.
     * Handles various error scenarios (insufficient funds, validation, etc.)
     *
     * API Endpoint: POST http://localhost:8000/api/cart/purchase
     * Authentication: Required (Bearer token)
     * Response: { message, cards_purchased, total_price }
     *
     * Flow:
     * 1. Set purchasing state to disable buttons
     * 2. Send POST request to purchase endpoint
     * 3. Handle errors (show error message, keep cart)
     * 4. On success: Show confirmation, clear cart, redirect to collection
     * 5. Reset purchasing state in finally block
     *
     * State Management:
     * - setPurchasing(true) disables purchase/clear buttons during API call
     * - Prevents duplicate purchases from double-clicks
     * - Always resets in finally block
     */
    const purchaseCart = async () => {
        // Set purchasing flag to true to disable buttons and show loading state
        // Prevents user from clicking purchase multiple times
        setPurchasing(true);

        // Get authentication token for API request
        const token = localStorage.getItem("token");

        try {
            // Send POST request to purchase endpoint
            // Backend processes payment, transfers cards to collection, clears cart
            const res = await fetch("http://localhost:8000/api/cart/purchase", {
                method: "POST", // POST method to create/process purchase
                headers: {
                    // Include Bearer token for authentication
                    "Authorization": `Bearer ${token}`
                }
            });

            // Check if purchase failed (status not 200-299)
            // Backend returns 400+ status codes for errors
            if (!res.ok) {
                // Parse error response to get detailed error message
                const error = await res.json();

                // Show error to user (e.g., "Insufficient funds", "Cart empty")
                alert(`❌ ${error.detail}`);

                // Exit function early - don't clear cart or redirect
                return;
            }

            // Purchase successful - parse response data
            // Contains: message, cards_purchased array, total_price
            const data = await res.json();

            // Show detailed success message with purchase summary
            // Includes: success message, list of cards, total amount spent
            alert(`🎉 ${data.message}\n\nCards purchased: ${data.cards_purchased.join(", ")}\nTotal: $${data.total_price.toFixed(2)}`);

            // Clear cart state immediately (cards now in collection)
            // No need to fetch - we know cart is empty after purchase
            setCartItems([]);

            // Redirect user to their collection page to see purchased cards
            // navigate() changes route without page reload
            navigate("/my-collection");
        } catch (err) {
            // Handle network errors, JSON parsing errors, or other exceptions
            // Show generic error message to user
            alert("Failed to complete purchase");
        } finally {
            // Finally block always executes, even if try or catch runs
            // Reset purchasing flag to re-enable buttons
            // Important: Ensures buttons are re-enabled even if error occurs
            setPurchasing(false);
        }
    };

    // ============================================================
    // COMPUTED VALUES
    // ============================================================

    /**
     * Calculate Total Cart Price
     *
     * Uses Array.reduce() to sum all card prices in cart.
     * Recalculates automatically whenever cartItems state changes.
     *
     * Algorithm:
     * - Start with sum = 0
     * - For each item, add item.card_price to sum
     * - Return final sum
     *
     * Example: [10.99, 5.99, 3.99] → 20.97
     */
    const totalPrice = cartItems.reduce((sum, item) => sum + item.card_price, 0);

    // ============================================================
    // CONDITIONAL RENDERING - LOADING STATE
    // ============================================================

    /**
     * Show Loading Spinner
     *
     * Early return pattern: If still loading, render loading UI and exit
     * Prevents rendering cart UI before data is fetched
     * User sees "Loading cart..." message while API call is in progress
     */
    if (loading) {
        return <div className="loading">Loading cart...</div>;
    }

    // ============================================================
    // MAIN RENDER - CART PAGE UI
    // ============================================================

    /**
     * Main Component Return
     *
     * Renders the complete cart page UI with:
     * - Header with title and back button
     * - Empty state or cart contents (conditional)
     * - Cart items list
     * - Cart summary with total and actions
     */
    return (
        // Main container for entire cart page
        <div className="cart-page">
            {/* ========================================
                CART HEADER
                ======================================== */}
            {/* Header section with page title and navigation */}
            <div className="cart-header">
                {/* Page title */}
                <h2>Shopping Cart</h2>

                {/* Back button to return to card browsing page */}
                {/* onClick uses inline arrow function to call navigate */}
                <button className="back-btn" onClick={() => navigate("/pokemon-cards")}>
                    ← Back to Cards
                </button>
            </div>

            {/* ========================================
                CONDITIONAL RENDERING: EMPTY vs FULL CART
                ======================================== */}
            {/* Ternary operator: if cart is empty, show empty state; else show cart items */}
            {cartItems.length === 0 ? (
                /* ========================================
                   EMPTY CART STATE
                   ======================================== */
                /* Shown when cartItems array has no elements */
                <div className="empty-cart">
                    {/* Shopping cart emoji icon */}
                    <div className="empty-icon">🛒</div>

                    {/* Empty state message heading */}
                    <h3>Your cart is empty</h3>

                    {/* Encouraging message to add cards */}
                    <p>Add some Pokemon cards to get started!</p>

                    {/* Button to navigate to card browsing page */}
                    {/* Helps user quickly start shopping */}
                    <button className="browse-btn" onClick={() => navigate("/pokemon-cards")}>
                        Browse Cards
                    </button>
                </div>
            ) : (
                /* ========================================
                   CART HAS ITEMS - SHOW CART CONTENTS
                   ======================================== */
                /* React Fragment (<>) groups multiple elements without extra DOM node */
                <>
                    {/* ========================================
                        CART ITEMS LIST
                        ======================================== */}
                    {/* Container for all cart item cards */}
                    <div className="cart-items">
                        {/* Map over cartItems array to render each item */}
                        {/* .map() creates a new array of JSX elements, one per cart item */}
                        {cartItems.map((item) => (
                            /* Individual cart item card */
                            /* key prop required for React list rendering optimization */
                            /* Uses item.id as unique identifier */
                            <div key={item.id} className="cart-item">
                                {/* Card image thumbnail */}
                                {/* src: URL to card image */}
                                {/* alt: Accessibility text for screen readers */}
                                <img src={item.card_image} alt={item.card_name} className="cart-item-image" />

                                {/* Card details section (name and price) */}
                                <div className="cart-item-details">
                                    {/* Card name heading */}
                                    <h3>{item.card_name}</h3>

                                    {/* Card price with $ symbol and 2 decimal places */}
                                    {/* toFixed(2) ensures format like 10.99, not 10.9 */}
                                    <div className="cart-item-price">${item.card_price.toFixed(2)}</div>
                                </div>

                                {/* Remove button to delete this item from cart */}
                                {/* onClick calls removeFromCart with item ID and name */}
                                {/* Inline arrow function passes parameters to removeFromCart */}
                                <button
                                    className="remove-btn"
                                    onClick={() => removeFromCart(item.id, item.card_name)}
                                >
                                    Remove
                                </button>
                            </div>
                        ))}
                    </div>

                    {/* ========================================
                        CART SUMMARY & ACTIONS
                        ======================================== */}
                    {/* Summary section showing totals and action buttons */}
                    <div className="cart-summary">
                        {/* Item count row */}
                        <div className="summary-row">
                            {/* Label for item count */}
                            <span>Items in cart:</span>

                            {/* Number of items (length of cartItems array) */}
                            {/* <strong> for visual emphasis */}
                            <strong>{cartItems.length}</strong>
                        </div>

                        {/* Total price row with emphasis styling */}
                        <div className="summary-row total">
                            {/* Label for total price */}
                            <span>Total:</span>

                            {/* Total calculated price with $ and 2 decimals */}
                            {/* Uses totalPrice computed value from reduce() */}
                            <strong>${totalPrice.toFixed(2)}</strong>
                        </div>

                        {/* Action buttons container */}
                        <div className="cart-actions">
                            {/* Clear Cart button - removes all items */}
                            {/* disabled when purchasing is true (during purchase API call) */}
                            {/* Prevents clearing cart during purchase process */}
                            <button
                                className="clear-btn"
                                onClick={clearCart}
                                disabled={purchasing}
                            >
                                Clear Cart
                            </button>

                            {/* Purchase button - processes the purchase */}
                            {/* disabled when purchasing is true (prevents double-click) */}
                            {/* Button text changes based on purchasing state */}
                            <button
                                className="purchase-btn"
                                onClick={purchaseCart}
                                disabled={purchasing}
                            >
                                {/* Conditional text: show "Processing..." during purchase, else "Purchase Now" */}
                                {/* Provides feedback that purchase is in progress */}
                                {purchasing ? "Processing..." : "Purchase Now"}
                            </button>
                        </div>

                        {/* Disclaimer note about demo payment */}
                        {/* Informs users this is not a real payment system */}
                        <p className="cart-note">
                            💳 Note: This is a demo. No actual payment will be processed.
                        </p>
                    </div>
                {/* End of cart contents fragment */}
                </>
            )}
        {/* End of cart-page container */}
        </div>
    );
}

// ============================================================
// EXPORT
// ============================================================

// Export Cart component as default export for use in routing
// Allows importing as: import Cart from './pages/Cart'

export default Cart;